### ISSUE TITLE
AWS Access Info 정리 및 확정

### ISSUE THREAD

**Issue by yjyj989812** [S0rrow/FPT5#90]
## TODO:
- [x] Access key 정리 또는 부여 확정
- [x]  AWS Access info json 파일 정리 및 확정
- [x] AWS 저장소 path info json 파일 정리 및 확정
----------
